### ISSUE TITLE
Access to XMLHttpRequest at 'https://code.quarkus.io/api/extensions' from origin 'http://localhost:3000' has been blocked by CORS policy

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-plugins#3]
## Issue

Axios calls reaching code.quarkus.io raises this error:
```
Access to XMLHttpRequest at 'https://code.quarkus.io/api/extensions' from origin 'http://localhost:3000' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

See: https://stackoverflow.com/questions/56297420/getting-network-error-when-calling-axios-get-request-in-react-js

![Screenshot 2024-01-11 at 15 57 08](https://github.com/q-shift/backstage-playground/assets/463790/db0807ae-83ff-488e-b564-6aa6405ba185)

It seems that we got a response as HTTP status is `200`
<img width="1727" alt="Screenshot 2024-01-11 at 21 26 52" src="https://github.com/q-shift/backstage-playground/assets/463790/f4f2a929-965b-44a2-b2a6-58c740efd7bc">

@iocanel Idea ?

**Comment by cmoulliard** [comment]
I replayed the steps described [here](https://github.com/q-shift/backstage-playground/blob/fc166baffc3a8bc40ce860c45b55b28de90c53d7/README.md) using a new backstage app and I'm still getting the CORS error.

@iocanel

**Comment by iocanel** [comment]
The issue was on server side and is now fixed.
