### ISSUE TITLE
Improve how we manage the plugins README.md and the parent README.md

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-plugins#60]
## TODO

Improve how we manage the plugins README.md and the parent README.md

## Description

Do you see a trick to merge the content of a README.md from subfolders into the parent README.md ?

Why ? To be able to see the README page of a backstage plugin: front, [console](https://github.com/q-shift/backstage-plugins/tree/main/plugins/quarkus-console) or backend (= subfolder of a git repository) on npmjs.org BUT also to see the whole documentation here on [main](https://github.com/q-shift/backstage-plugins/blob/main/README.md)

**Comment by jacobdotcosta** [comment]
Would it do to implement a template/macro based solution? 

The solution could be to have a markdown template with the main `README.md` contents and includes to the different sub-folder `README.md` files. Generating the final `README.md` file could either be done locally using with a PR  or during the release process.

Something like what's proposed on [this stackoverflow comment](https://stackoverflow.com/a/36104553) that uses the [GNU M4](https://www.gnu.org/software/m4/) macro processor.

**Comment by cmoulliard** [comment]
Can you create a small prototype using m4 tool ? Is m4 available part of the ubuntu image used by the github jobs ?
@jacobdotcosta

**Comment by jacobdotcosta** [comment]
@cmoulliard , I created a sample using the [GNU M4](https://www.gnu.org/software/m4/)  macro processor.

On the [jacobdotcosta/github-workflow-test](https://github.com/jacobdotcosta/github-workflow-test) project there is a template file named `README.m4.template.md` that generates the `README.m4.result.md` markdown. The includes are implemented at the bottom of the template to add the 3 README of the plugins to the file.

```m4
include(""""./plugins/quarkus/README.md""")
include(""""./plugins/quarkus-backend/README.md""")
include(""""./plugins/quarkus-console/README.md""")
```
The command used to generate the result markdown was the following.

```bash
$ m4 README.m4.template.md > README.m4.result.md
```

**Comment by cmoulliard** [comment]
Can you then add enhance our existing flow(s) to include a step to executed when the commit or PR includes *.md changes to generate the new root md file and push it as change ?

**Comment by jacobdotcosta** [comment]
I was wondering, should the main `README.md` file be updated only when the PR is merged? 

@cmoulliard

**Comment by cmoulliard** [comment]
> I was wondering, should the main `README.md` file be updated only when the PR is merged?

If we don't push a commit directly but we use only PR, then I'm fine to make the change when merged
