### ISSUE TITLE
Relative link to image don't work anymore when README parent is generated

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-plugins#97]
## Issue

Relative link to image don't work anymore when README parent is generated

![Screenshot 2024-05-03 at 14 40 41](https://github.com/q-shift/backstage-plugins/assets/463790/204973e8-63ab-4885-a2e2-aaf3330e305e)

**Comment by jacobdotcosta** [comment]
This happens because the URL to the image is relative to the location of the markdown file.  I think this should work if the link to the file is relative to the repository root. Will make a test.

**Comment by jacobdotcosta** [comment]
All the links to resources under the repository must have links relative to the repository root, _i.e._ `/`.

Check the example on https://github.com/jacobdotcosta/github-workflow-test/ where the image for the "_Quarkus Version list - Recommended (field):_" label is referring the repository root and is visible both from the root README as well as the plugins/quarkus/README file.

**Comment by cmoulliard** [comment]
> Check the example on https://github.com/jacobdotcosta/github-workflow-test/ where the image for the "_Quarkus Version list - Recommended (field):_" label is referring the repository root and is visible both from the root README as well as the plugins/quarkus/README file.

That will work at the level of the root - parent README.md file but then the image will not be visible anymore at the level of the plugin, which is also published on npmjs !

**Comment by jacobdotcosta** [comment]
If you check my example the image is also seen on the README.md file under the quarkus plugin sub-folder.

https://github.com/jacobdotcosta/github-workflow-test/blob/main/plugins/quarkus/README.md

![image](https://github.com/q-shift/backstage-plugins/assets/19552717/e86bd6c6-e391-4229-93fa-de3a044641db)
